<a href="https://colab.research.google.com/github/nishantkj911/deep-learning-models/blob/alternate_method/single_layer_perceptron_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow==2.0

     |████████████████████████████████| 86.3MB 75kB/s 
     |████████████████████████████████| 450kB 40.9MB/s 
     |████████████████████████████████| 3.8MB 49.0MB/s 
     |████████████████████████████████| 81kB 11.6MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstall

In [2]:
import tensorflow as tf
import numpy as np
tf.version

<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v2/version/__init__.py'>

In [0]:
# create the dataset
np.random.seed(1)

arr = np.random.rand(10000)
mean = arr.mean()
arr = arr - mean
x = arr + 0.4
mean = arr.mean()
y = (arr > mean).astype(float)

In [0]:
# create the model

# initialize the input and output variables
x_tensor = tf.convert_to_tensor(x, dtype=float)
y_tensor = tf.convert_to_tensor(y, dtype=float)

# initialize the weight and bias
tf.random.set_seed(1)
w = tf.random.normal([1])
b = tf.random.normal([1])

v = tf.zeros(x_tensor.shape)
e = tf.zeros(x_tensor.shape)
y_hat = tf.zeros(x_tensor.shape)

In [5]:
print(x_tensor)
print(y_tensor)
print(w)
print(b)

tf.Tensor(
[ 0.31902558  0.62232804 -0.09788206 ... -0.03846274  0.01004722
  0.66479737], shape=(10000,), dtype=float32)
tf.Tensor([0. 1. 0. ... 0. 0. 1.], shape=(10000,), dtype=float32)
tf.Tensor([-1.1012203], shape=(1,), dtype=float32)


NameError: ignored

In [0]:
# describe the error/cost function
def model(x, w, b):
    v = w * x + b
    y_hat = tf.round(tf.nn.sigmoid(v))
        
    return y_hat

def loss_function(y, y_hat):
    e = y - y_hat
    E = 0.5 * (e * e)
    return E

In [0]:
def train_one_iter(x, y, w, b, learning_rate=0.001):
    learning_rate_tensor = tf.convert_to_tensor(learning_rate)
    with tf.GradientTape() as t:
        t.watch(w)
        t.watch(b)
        y_hat = model(x, w, b)
        E = loss_function(y, y_hat)
    dw, db = t.gradient(E, [w, b])
    print(dw, db)
    # w = w - (learning_rate_tensor * dw)
    # b = b - (learning_rate_tensor * db)
    return w, b

In [13]:
print("w: ", w.numpy())
for i in range(0, x_tensor.shape[0]):
    w = train_one_iter(x_tensor[i], y_tensor[i], w)
    print("Iter -", i, " w: ", w.numpy())

w:  [-1.1012203]
None
Iter - 0  w:  [-1.1012203]
None
Iter - 1  w:  [-1.1012203]
None
Iter - 2  w:  [-1.1012203]
None
Iter - 3  w:  [-1.1012203]
None
Iter - 4  w:  [-1.1012203]
None
Iter - 5  w:  [-1.1012203]
None
Iter - 6  w:  [-1.1012203]
None
Iter - 7  w:  [-1.1012203]
None
Iter - 8  w:  [-1.1012203]
None
Iter - 9  w:  [-1.1012203]
None
Iter - 10  w:  [-1.1012203]
None
Iter - 11  w:  [-1.1012203]
None
Iter - 12  w:  [-1.1012203]
None
Iter - 13  w:  [-1.1012203]
None
Iter - 14  w:  [-1.1012203]
None
Iter - 15  w:  [-1.1012203]
None
Iter - 16  w:  [-1.1012203]
None
Iter - 17  w:  [-1.1012203]
None
Iter - 18  w:  [-1.1012203]
None
Iter - 19  w:  [-1.1012203]
None
Iter - 20  w:  [-1.1012203]
None
Iter - 21  w:  [-1.1012203]
None
Iter - 22  w:  [-1.1012203]
None
Iter - 23  w:  [-1.1012203]
None
Iter - 24  w:  [-1.1012203]
None
Iter - 25  w:  [-1.1012203]
None
Iter - 26  w:  [-1.1012203]
None
Iter - 27  w:  [-1.1012203]
None
Iter - 28  w:  [-1.1012203]
None
Iter - 29  w:  [-1.1012203]
Non

KeyboardInterrupt: ignored